SSLError
requests.exceptions.SSLError: HTTPSConnectionPool(host='ifsdev.atlassian.net', port=443): Max retries exceeded with url: /rest/api/3/search (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1000)')))

Traceback (most recent call last)
File "C:\Program Files\Python312\Lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
